version: '3.8'
services:
  user-mangement:
    container_name: user-management
    image: dashboard/user-management:1.0-SNAPSHOT
    ports:
      - '8081:8081'
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /jwt/publicKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
  authentication-jwt:
    container_name: authentication-jwt
    image: dashboard/jwt:1.0-SNAPSHOT
    ports:
      - '8082:8082'
    environment:
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt